

name: Continuos Integration
on: 
  push:
    branches: 
      - main


jobs:

  flutter_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build_appbundle: 
    name: Build Android App Bundle
    needs: flutter_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build appbundle